version: 0.2
phases:
  pre_build:
    commands:
      - echo In the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/spring-boot-with-kafka-0.0.1-SNAPSHOT.jar spring-boot-with-kafka-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - spring-boot-with-kafka-0.0.1-SNAPSHOT.jar
    - .ebextensions/**/*